Update translations_de.yml
elorz007/wedding pull request #2
Opened 2022-01-31 18:24 UTC by MontseVo

2022-01-31 21:03 UTC, elorz007 requested changes

2022-01-31 21:03 UTC, elorz007 commented on translations_de.yml
> +    text: 'Die Perle des Baskenlandes, eine Stunde mit dem Auto oder dem <a target="_blank" href="https://www.alsa.es/">Bus</a> entfernt (ca. 17 € Hin- und Rückfahrt). Ein Spaziergang entlang der Pro
Gansefüßchen überall

2022-02-01 18:46 UTC, MontseVo commented on translations_de.yml
> +    title: '**TODO TRANSLATE**Urbasa und die Quelle der Urederra'
done

2022-02-01 18:46 UTC, MontseVo commented on translations_de.yml
> +    title: '**TODO TRANSLATE**Urbasa und die Quelle der Urederra'
i di et

2022-02-01 18:50 UTC, MontseVo commented on translations_de.yml
> +      title: 'Unterkünfte auf Airbnb suchen (vermeidet dabei die touristischen "Sanfermines"-Unterkünfte)'
done

2022-02-01 18:52 UTC, MontseVo commented on translations_de.yml
> +  summary_food: 'In Pamplona gibt es auch viele <strong>Bars und Restaurants</strong>, wo ihr etwas trinken, ein paar Pintxos essen oder eine Mahlzeit genießen könnt. Wir empfehlen euch auch, einmal
ignored

2022-02-01 18:53 UTC, MontseVo commented on translations_de.yml
> +  summary: 'Navarra bietet eine große Vielfalt an Sehenswürdigkeiten - von üppigen Wälder bis hin zu Wüsten und mitteralterlichen Burgen. Nachfolgend findet ihr einige Ideen für interessante Orte, di
done

2022-02-01 18:57 UTC, MontseVo commented on translations_de.yml
> +    text: 'Die bekanntesten Wasserfälle in Navarra "Urederra", was auf Baskisch "schöne Gewässer" bedeutet. Dieser Fluss mit seinen türkisfarbenen Farben kann mit der ganzen Familie besucht werden. B
done

2022-02-01 18:58 UTC, MontseVo commented on translations_de.yml
> +    text: 'Die Perle des Baskenlandes, eine Stunde mit dem Auto oder dem <a target="_blank" href="https://www.alsa.es/">Bus</a> entfernt (ca. 17 € Hin- und Rückfahrt). Ein Spaziergang entlang der Pro
done

2022-02-01 19:22 UTC, elorz007 approved these changes

2022-02-01 19:22 UTC, merged